### ISSUE TITLE
Cant find logo image in public folder when accessed from something else then the base path

### ISSUE THREAD

**Issue by crazyvinvin** [MCSEvolved/Navbar#1]
The logo in the public folder can't be found when you access from a URL like:
`http://localhost:5555/something/else`

It can be found from:
`http://localhost:5555/something`
and from
`http://localhost:5555/`

when doing:
`http://localhost:5555/something/else`
it looks for the image at `/something` but the image is in the public folder, so it's located at the base `http://localhost:5555/`

I can work around this by putting it in a folder named `/something/` but once I go to `/something/else/again`, this would not work anymore.

**Comment by IICarst** [comment]
The problem is that vite doesn't update your logoSrc if you just hardcode the string.
Try importing the image like they do here to fix this: https://vitejs.dev/guide/assets.html#importing-asset-as-url

Let me know if it works

**Comment by IICarst** [comment]
I tried it in the admin panel frontend and there it works

**Comment by crazyvinvin** [comment]
Yes, that seems to work. 

For future reference, here is the code I am using now (React): 
```javascript
import logo from '../public/logo.svg';
export default function Layout() {
    return (
        <>
            <mcs-navbar logoSrc={logo}></mcs-navbar>
            <App></App>
        </>
    )
}
```

**Comment by crazyvinvin** [comment]
the import was giving me some warnings, changed it to:
```javascript
import logo from '/logo.svg?url';
```
