### ISSUE TITLE
Change redirect link that's used when clicking the logo

### ISSUE THREAD

**Issue by crazyvinvin** [MCSEvolved/Navbar#2]
currently, clicking the logo sends you back to `https://mcsynergy.nl/`. I think it's better if (in case of the tracker) it sends you back to `https://mcsynergy.nl/tracker`. Please allow us to change the redirect url, for example by adding an extra OPTIONAL property to the svelte component.

**Comment by IICarst** [comment]
fixed in commit: 2a2d0f4
